"use client";

import { useEffect, useMemo, useState } from "react";
import useSWR from "swr";
import { Activity, AlertTriangle, Bot, CheckCircle2, ChevronRight, CircleAlert, Database, Gauge, GitBranch, Search, ShieldCheck, Sparkles, TrendingUp } from "lucide-react";
import { cn } from "@/lib/utils";
import type { AlertCategory, IntelligenceAlert, IntelligenceSnapshot, Severity } from "@/lib/intelligence/types";

const fetcher = (url: string) => fetch(url).then((response) => { if (!response.ok) throw new Error("Unable to load intelligence data"); return response.json(); });
type Tab = "alerts" | "kpis" | "activity" | "monitoring";
const tabs: { id: Tab; label: string; icon: typeof Activity }[] = [{ id: "alerts", label: "Alert Center", icon: CircleAlert }, { id: "kpis", label: "KPI Opportunities", icon: Sparkles }, { id: "activity", label: "Activity", icon: Activity }, { id: "monitoring", label: "Monitoring", icon: Gauge }];
const filters: { id: "all" | Severity | AlertCategory; label: string }[] = [{ id: "all", label: "All" }, { id: "critical", label: "Critical" }, { id: "kpi", label: "KPI" }, { id: "reports", label: "Reports" }, { id: "datasets", label: "Datasets" }, { id: "agents", label: "Agents" }, { id: "database", label: "DB" }, { id: "security", label: "Security" }];
const severityStyle: Record<Severity, string> = { critical: "bg-destructive text-primary-foreground", error: "bg-destructive/15 text-destructive", warning: "bg-accent text-accent-foreground", success: "bg-primary/12 text-primary", info: "bg-muted text-muted-foreground" };

export function IntelligenceCenter() {
  const { data, error, isLoading, mutate } = useSWR<IntelligenceSnapshot>("/api/intelligence", fetcher, { refreshInterval: 30000 });
  const [tab, setTab] = useState<Tab>("alerts"); const [filter, setFilter] = useState<string>("all"); const [query, setQuery] = useState(""); const [selectedId, setSelectedId] = useState<string>();
  useEffect(() => { const stream = new EventSource("/api/intelligence/stream"); const refresh = () => void mutate(); ["alerts/new", "alerts/updated", "kpi/detected", "dataset/changed", "report/published", "agent/failed"].forEach((name) => stream.addEventListener(name, refresh)); stream.onerror = () => stream.close(); return () => stream.close(); }, [mutate]);
  const alerts = useMemo(() => (data?.alerts ?? []).filter((alert) => (filter === "all" || alert.severity === filter || alert.category === filter) && `${alert.title} ${alert.description} ${alert.entityName}`.toLowerCase().includes(query.toLowerCase())), [data, filter, query]);
  const selected = alerts.find((alert) => alert.id === selectedId) ?? alerts[0];
  async function updateAlert(alert: IntelligenceAlert, action: "read" | "resolve" | "reopen") { await fetch(`/api/alerts/${alert.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }); await mutate(); }
  if (isLoading) return <div className="h-96 animate-pulse rounded-xl bg-muted" aria-label="Loading intelligence center" />;
  if (error || !data) return <div className="rounded-xl border border-destructive/30 bg-destructive/10 p-6 text-sm text-destructive">Intelligence data is temporarily unavailable.</div>;
  return <div className="flex flex-col gap-5">
    <section className="flex flex-col gap-4 rounded-xl border border-border bg-card p-5 lg:flex-row lg:items-center lg:justify-between">
      <div><div className="mb-2 flex items-center gap-2 text-xs font-medium text-primary"><Sparkles className="size-4" /> Operational intelligence</div><h2 className="text-balance text-2xl font-semibold text-foreground">Intelligent Alerts & KPI Detection Center</h2><p className="mt-1 max-w-3xl text-sm leading-relaxed text-muted-foreground">Correlated healthcare KPI, data quality, agent, and platform signals—with lineage and impact analysis.</p></div>
      <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{Object.entries(data.scores).map(([key, value]) => <Score key={key} label={key.replace(/([A-Z])/g, " $1")} value={value} />)}</div>
    </section>
    <nav className="flex overflow-x-auto rounded-lg border border-border bg-card p-1" aria-label="Intelligence Center sections">{tabs.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={cn("flex shrink-0 items-center gap-2 rounded-md px-4 py-2 text-sm font-medium transition-colors", tab === id ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted hover:text-foreground")}><Icon className="size-4" />{label}</button>)}</nav>
    {tab === "alerts" && <><div className="flex flex-col gap-3 rounded-lg border border-border bg-card p-3 lg:flex-row lg:items-center"><label className="flex flex-1 items-center gap-2 rounded-md border border-input bg-background px-3 py-2"><Search className="size-4 text-muted-foreground" /><span className="sr-only">Search alerts</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search alerts, assets, and source systems" className="w-full bg-transparent text-sm outline-none placeholder:text-muted-foreground" /></label><div className="flex gap-1 overflow-x-auto">{filters.map((item) => <button key={item.id} onClick={() => setFilter(item.id)} className={cn("shrink-0 rounded-md px-3 py-2 text-xs font-medium", filter === item.id ? "bg-secondary text-secondary-foreground" : "text-muted-foreground hover:bg-muted")}>{item.label}</button>)}</div></div><div className="grid min-h-[480px] overflow-hidden rounded-xl border border-border bg-card lg:grid-cols-[minmax(280px,0.9fr)_minmax(380px,1.35fr)]"><div className="border-b border-border lg:border-b-0 lg:border-r"><div className="flex items-center justify-between border-b border-border px-4 py-3"><span className="text-sm font-medium">{alerts.length} alerts</span><span className="text-xs text-muted-foreground">Live</span></div><div className="max-h-[620px] overflow-y-auto">{alerts.map((alert) => <button key={alert.id} onClick={() => { setSelectedId(alert.id); if (alert.status === "open") void updateAlert(alert, "read"); }} className={cn("flex w-full gap-3 border-b border-border/60 p-4 text-left transition-colors hover:bg-muted/50", selected?.id === alert.id && "bg-muted")}><span className={cn("mt-0.5 rounded-full px-2 py-1 text-[10px] font-semibold uppercase", severityStyle[alert.severity])}>{alert.severity}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium text-foreground">{alert.title}</span><span className="mt-1 block truncate text-xs text-muted-foreground">{alert.sourceSystem} · {relativeTime(alert.createdAt)}</span></span><ChevronRight className="size-4 shrink-0 text-muted-foreground" /></button>)}</div></div>{selected ? <AlertDetails alert={selected} onAction={updateAlert} /> : <div className="flex items-center justify-center p-8 text-sm text-muted-foreground">No alerts match this filter.</div>}</div></>}
    {tab === "kpis" && <div className="grid gap-4 lg:grid-cols-2">{data.kpis.map((kpi) => <article key={kpi.id} className="rounded-xl border border-border bg-card p-5"><div className="flex items-start justify-between gap-3"><div><span className="text-xs font-medium text-primary">{kpi.businessCategory}</span><h3 className="mt-1 text-base font-semibold text-foreground">{kpi.name}</h3></div><span className={cn("rounded-full px-2 py-1 text-[10px] font-semibold uppercase", kpi.status === "detected" ? "bg-accent text-accent-foreground" : "bg-primary/10 text-primary")}>{kpi.status}</span></div><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{kpi.description}</p><div className="mt-4 rounded-md bg-muted p-3 font-mono text-xs text-foreground">{kpi.formula}</div><div className="mt-4 flex items-center justify-between text-xs"><span className="text-muted-foreground">Confidence {Math.round(kpi.confidence * 100)}%</span><span className="flex items-center gap-1 text-primary"><GitBranch className="size-3" /> {kpi.lineage.length} lineage nodes</span></div></article>)}</div>}
    {tab === "activity" && <div className="rounded-xl border border-border bg-card"><div className="border-b border-border px-5 py-4"><h3 className="font-semibold">Operational activity</h3><p className="text-xs text-muted-foreground">Events feeding KPI detection and alert correlation.</p></div>{data.activity.map((event) => <div key={event.id} className="flex items-start gap-3 border-b border-border/60 px-5 py-4 last:border-0"><span className="rounded-full bg-primary/10 p-2 text-primary"><Activity className="size-4" /></span><div className="min-w-0 flex-1"><p className="text-sm font-medium">{event.eventType}</p><p className="mt-1 text-xs text-muted-foreground">{event.entityName} · {event.sourceSystem} · {relativeTime(event.eventDate)}</p></div></div>)}</div>}
    {tab === "monitoring" && <div className="grid gap-5 xl:grid-cols-2"><MonitorPanel title="Agent monitoring" icon={Bot}>{data.agents.map((agent) => <div key={agent.id} className="grid grid-cols-[1fr_auto] gap-2 border-b border-border/60 py-3 last:border-0"><div><p className="text-sm font-medium">{agent.name}</p><p className="text-xs text-muted-foreground">{agent.executions.toLocaleString()} executions · {agent.averageResponseMs}ms avg</p></div><span className={cn("text-xs font-semibold", agent.status === "healthy" ? "text-primary" : "text-accent-foreground")}>{agent.successRate}%</span></div>)}</MonitorPanel><MonitorPanel title="Database monitoring" icon={Database}>{data.database.map((metric) => <div key={metric.name} className="flex items-center justify-between border-b border-border/60 py-3 last:border-0"><div><p className="text-sm font-medium">{metric.name}</p><p className="text-xs text-muted-foreground">Trend {metric.trend > 0 ? "+" : ""}{metric.trend}%</p></div><span className="text-sm font-semibold">{metric.value.toLocaleString()} <span className="text-xs font-normal text-muted-foreground">{metric.unit}</span></span></div>)}</MonitorPanel></div>}
  </div>;
}
function Score({ label, value }: { label: string; value: number }) { return <div className="min-w-28 rounded-lg bg-muted px-3 py-2"><div className="text-xl font-semibold text-foreground">{value}</div><div className="capitalize text-[10px] text-muted-foreground">{label}</div></div>; }
function AlertDetails({ alert, onAction }: { alert: IntelligenceAlert; onAction: (alert: IntelligenceAlert, action: "read" | "resolve" | "reopen") => void }) { return <article className="flex flex-col"><header className="border-b border-border p-5"><div className="flex items-start justify-between gap-3"><div><span className={cn("rounded-full px-2 py-1 text-[10px] font-semibold uppercase", severityStyle[alert.severity])}>{alert.severity}</span><h3 className="mt-3 text-xl font-semibold text-foreground">{alert.title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{alert.description}</p></div><AlertTriangle className="size-5 shrink-0 text-accent-foreground" /></div></header><div className="flex flex-1 flex-col gap-5 p-5"><Detail title="Timeline"><p>{new Date(alert.createdAt).toLocaleString()} · {alert.sourceSystem}</p></Detail><Detail title="Impacted assets"><div className="flex flex-wrap gap-2">{alert.impactedAssets.map((asset) => <span key={asset} className="rounded-md border border-border bg-muted px-2 py-1 text-xs">{asset}</span>)}</div></Detail><Detail title="Resolution actions"><ul className="flex flex-col gap-2">{alert.resolutionActions.map((action) => <li key={action} className="flex items-center gap-2"><CheckCircle2 className="size-4 text-primary" />{action}</li>)}</ul></Detail></div><footer className="flex justify-end gap-2 border-t border-border bg-muted/40 p-4"><button onClick={() => onAction(alert, alert.status === "resolved" ? "reopen" : "resolve")} className="rounded-md bg-primary px-4 py-2 text-xs font-medium text-primary-foreground">{alert.status === "resolved" ? "Reopen" : "Resolve alert"}</button></footer></article>; }
function Detail({ title, children }: { title: string; children: React.ReactNode }) { return <section><h4 className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">{title}</h4><div className="text-sm text-foreground">{children}</div></section>; }
function MonitorPanel({ title, icon: Icon, children }: { title: string; icon: typeof Bot; children: React.ReactNode }) { return <section className="rounded-xl border border-border bg-card"><header className="flex items-center gap-2 border-b border-border px-5 py-4"><Icon className="size-4 text-primary" /><h3 className="font-semibold">{title}</h3></header><div className="px-5">{children}</div></section>; }
function relativeTime(value: string) { const minutes = Math.max(1, Math.round((Date.now() - new Date(value).getTime()) / 60000)); return minutes < 60 ? `${minutes}m ago` : `${Math.round(minutes / 60)}h ago`; }
