/**
 * POST /api/kpi/interpret
 *
 * Accepts a saved report name, its row data, the KPI type, and the date range,
 * then returns a structured BusinessInsights JSON object generated by GPT-4o-mini.
 *
 * Body:
 *   report_name   string
 *   kpi           string           — admissions | discharges | revenue | census
 *   start_date    string           — YYYY-MM-DD
 *   end_date      string           — YYYY-MM-DD
 *   data          Record[]         — the result rows (max 200 sent to the model)
 *   columns       string[]         — column names from the result
 */

import { NextRequest, NextResponse } from "next/server";
import { generateText, Output } from "ai";
import { z } from "zod";
import { getModel, getModelId } from "@/lib/ai/gateway";

// ── Output schema ─────────────────────────────────────────────────────────────

const TrendSchema = z.object({
  label: z.string(),
  direction: z.enum(["up", "down", "flat"]),
  magnitude: z.string().nullable(),
  insight: z.string(),
});

const AlertSchema = z.object({
  severity: z.enum(["high", "medium", "low"]),
  title: z.string(),
  detail: z.string(),
  recommended_action: z.string(),
});

const SegmentSchema = z.object({
  segment: z.string(),
  value: z.string(),
  share_of_total: z.string().nullable(),
  commentary: z.string(),
});

const BusinessInsightsSchema = z.object({
  summary: z.string().describe("2-3 sentence executive summary of the report period"),
  period_label: z.string().describe("Human-readable description of the date range e.g. 'Week 24, June 2026'"),
  headline_metric: z.object({
    label: z.string(),
    value: z.string(),
    context: z.string(),
  }),
  trends: z.array(TrendSchema).describe("2-4 key trends observed in the data"),
  top_segments: z.array(SegmentSchema).describe("Top 3-5 performing or notable segments (branches, regions, etc.)"),
  alerts: z.array(AlertSchema).describe("0-3 actionable alerts or anomalies that warrant attention"),
  opportunities: z.array(z.string()).describe("2-3 data-backed opportunities or recommendations"),
  data_quality_notes: z.array(z.string()).nullable().describe("Any data gaps, nulls, or anomalies noticed in the raw data"),
  confidence: z.enum(["high", "medium", "low"]).describe("Confidence level in these insights based on data completeness"),
});

export type BusinessInsights = z.infer<typeof BusinessInsightsSchema>;

// ── Route handler ─────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { report_name, kpi, start_date, end_date, data, columns } = body;

    if (!data || !Array.isArray(data) || data.length === 0) {
      return NextResponse.json({ error: "data array is required and must not be empty" }, { status: 400 });
    }

    // Cap rows sent to the model to avoid token limits
    const sample = data.slice(0, 200);

    const systemPrompt = `You are a senior healthcare analytics consultant specialising in home health and hospice operations.
You will receive raw report data from the AcaciaHealth reporting engine and produce structured business insights.

Rules:
- Be precise and data-driven. Reference actual numbers from the data.
- Use healthcare / home health domain language (census, SOC, discharge, branch, etc.).
- Alerts should be specific and actionable — not generic.
- Opportunities must be grounded in the numbers, not generic advice.
- Never hallucinate numbers that are not in the data.
- Confidence = "high" if data covers a full period with no nulls, "medium" if partial, "low" if sparse or heavily demo data.`;

    const userMessage = `Analyse the following KPI report and return a BusinessInsights object.

Report: "${report_name}"
KPI: ${kpi}
Date range: ${start_date} to ${end_date}
Columns: ${columns?.join(", ") ?? "unknown"}
Row count: ${data.length}

Data sample (up to 200 rows):
${JSON.stringify(sample, null, 2)}

Return a complete BusinessInsights JSON object.`;

    const modelId = getModelId("default");

    const result = await generateText({
      model: getModel("default"),
      system: systemPrompt,
      prompt: userMessage,
      experimental_output: Output.object({ schema: BusinessInsightsSchema }),
      temperature: 0.2,
    });

    const insights = result.experimental_output as BusinessInsights;

    return NextResponse.json({
      insights,
      meta: {
        model: modelId,
        row_count: data.length,
        sample_count: sample.length,
        generated_at: new Date().toISOString(),
      },
    });
  } catch (err) {
    console.error("[v0] /api/kpi/interpret error:", err);

    // Graceful fallback — return static demo insights when AI is not configured
    const fallback: BusinessInsights = await buildDemoInsights(req);
    return NextResponse.json({
      insights: fallback,
      meta: {
        model: "demo-fallback",
        row_count: 0,
        sample_count: 0,
        generated_at: new Date().toISOString(),
        fallback: true,
      },
    });
  }
}

// ── Demo fallback (shown when AI_GATEWAY_API_KEY is not set) ──────────────────

async function buildDemoInsights(req: NextRequest): Promise<BusinessInsights> {
  let kpi = "admissions";
  try {
    const body = await req.clone().json();
    kpi = body.kpi ?? "admissions";
  } catch {}

  const insightMap: Record<string, BusinessInsights> = {
    admissions: {
      summary:
        "The selected period shows moderate admission volume with a concentration in the Eastern and Gulf Coast branches. Week-over-week trends indicate a slight uptick in home health admissions while hospice referrals remain stable.",
      period_label: "Current Reporting Period",
      headline_metric: { label: "Total Admissions", value: "247", context: "Across all active branches in the selected date range" },
      trends: [
        { label: "Home Health Admissions", direction: "up", magnitude: "+8%", insight: "Eastern branches are driving growth, particularly Charlotte and Raleigh." },
        { label: "Hospice Admissions", direction: "flat", magnitude: "0%", insight: "Hospice referral volume is holding steady — no significant change detected." },
        { label: "Weekend Admissions", direction: "down", magnitude: "-12%", insight: "Weekend SOC events are down compared to the prior period — may indicate staffing constraints." },
      ],
      top_segments: [
        { segment: "Charlotte Branch", value: "58 admissions", share_of_total: "23%", commentary: "Top performer — consistently above the branch average." },
        { segment: "Raleigh Branch", value: "44 admissions", share_of_total: "18%", commentary: "Strong growth trajectory, up from 38 in the prior period." },
        { segment: "Gulf Coast Branch", value: "39 admissions", share_of_total: "16%", commentary: "Consistent mid-tier volume with room for referral source expansion." },
      ],
      alerts: [
        { severity: "medium", title: "Low weekend SOC rate", detail: "Weekend admissions are 12% below the rolling 4-week average.", recommended_action: "Review weekend on-call staffing levels and referral source follow-up cadence." },
      ],
      opportunities: [
        "Expand referral source outreach in Gulf Coast to close the gap with Charlotte.",
        "Investigate the weekend SOC gap — a structured on-call protocol could recover 10-15 admissions per month.",
        "Raleigh growth trajectory suggests capacity for a dedicated hospice liaison hire.",
      ],
      data_quality_notes: ["Running in demo mode — data is illustrative only."],
      confidence: "low",
    },
    revenue: {
      summary:
        "Revenue for the period totals approximately $1.24M across all active branches with billing concentration in home health service lines. Two branches show below-average revenue-per-episode ratios that may indicate billing lag or denial activity.",
      period_label: "Current Reporting Period",
      headline_metric: { label: "Total Revenue", value: "$1,240,000", context: "Billed revenue across all service lines in the selected period" },
      trends: [
        { label: "Home Health Revenue", direction: "up", magnitude: "+5%", insight: "Home health billing is trending upward driven by higher episode counts." },
        { label: "Hospice Revenue", direction: "down", magnitude: "-3%", insight: "Slight dip in hospice billing — could reflect timing or discharge pattern changes." },
        { label: "Revenue per Episode", direction: "flat", magnitude: null, insight: "Revenue per episode is stable at approximately $5,020 on average." },
      ],
      top_segments: [
        { segment: "Charlotte Branch", value: "$318,400", share_of_total: "26%", commentary: "Highest revenue branch — consistent with admission volume leadership." },
        { segment: "Raleigh Branch", value: "$241,200", share_of_total: "19%", commentary: "Revenue growth tracking with admission increase." },
        { segment: "Gulf Coast Branch", value: "$196,000", share_of_total: "16%", commentary: "Below-average revenue per episode — review billing patterns." },
      ],
      alerts: [
        { severity: "high", title: "Gulf Coast revenue per episode below threshold", detail: "Revenue per episode in Gulf Coast is $4,200 vs a $5,000 target.", recommended_action: "Audit recent claims for denial patterns and late billing submissions." },
      ],
      opportunities: [
        "Gulf Coast billing audit could recover an estimated $15,000-$25,000 in delayed or denied claims.",
        "Hospice revenue dip warrants a review of discharge timing to ensure proper billing period capture.",
        "Consider a revenue integrity review of the two lowest-performing branches for coding accuracy.",
      ],
      data_quality_notes: ["Running in demo mode — data is illustrative only."],
      confidence: "low",
    },
    census: {
      summary:
        "Active census stands at 312 patients across all care types with home health comprising 68% of the total. Hospice census has grown 4% period-over-period, while the paediatric census remains an outlier requiring monitoring.",
      period_label: "Current Reporting Period",
      headline_metric: { label: "Active Census", value: "312 patients", context: "Distinct active patients as of the end of the reporting period" },
      trends: [
        { label: "Home Health Census", direction: "up", magnitude: "+3%", insight: "Steady growth consistent with admission trends." },
        { label: "Hospice Census", direction: "up", magnitude: "+4%", insight: "Hospice census growing faster than home health — may require capacity planning." },
        { label: "Paediatric Census", direction: "down", magnitude: "-20%", insight: "Sharp drop in paediatric census — verify discharge coding accuracy." },
      ],
      top_segments: [
        { segment: "Home Health", value: "212 patients", share_of_total: "68%", commentary: "Dominant service line — stable and growing." },
        { segment: "Hospice", value: "86 patients", share_of_total: "28%", commentary: "Growing share of census — watch for capacity constraints." },
        { segment: "Paediatric", value: "14 patients", share_of_total: "4%", commentary: "Small volume with a notable recent drop — investigate." },
      ],
      alerts: [
        { severity: "medium", title: "Paediatric census decline", detail: "Paediatric census dropped 20% from the prior period with no corresponding increase in discharges.", recommended_action: "Confirm all paediatric admissions and discharges are accurately recorded in HCHB." },
      ],
      opportunities: [
        "Hospice growth trajectory justifies evaluating a dedicated hospice liaison for high-referral markets.",
        "Home health census stability provides a solid baseline for branch-level capacity planning.",
        "Paediatric programme audit could clarify whether the drop is a data issue or a true volume trend.",
      ],
      data_quality_notes: ["Running in demo mode — data is illustrative only."],
      confidence: "low",
    },
    discharges: {
      summary:
        "Discharge volume for the period is 198 episodes with a goal-met discharge rate of 62%. A concentration of non-goal discharges in two branches warrants clinical review.",
      period_label: "Current Reporting Period",
      headline_metric: { label: "Total Discharges", value: "198", context: "All discharge events in the selected date range" },
      trends: [
        { label: "Goal-Met Discharges", direction: "up", magnitude: "+6%", insight: "Outcome quality improving — goal attainment rate rising across most branches." },
        { label: "Hospitalisation Discharges", direction: "down", magnitude: "-4%", insight: "Fewer hospital-related discharges — a positive clinical quality signal." },
        { label: "Non-Goal Discharges", direction: "up", magnitude: "+9%", insight: "Concentrated in two branches — may reflect patient population acuity changes." },
      ],
      top_segments: [
        { segment: "Charlotte Branch", value: "52 discharges", share_of_total: "26%", commentary: "Highest volume — 68% goal-met rate, above network average." },
        { segment: "Raleigh Branch", value: "38 discharges", share_of_total: "19%", commentary: "Strong goal-met rate at 65%." },
        { segment: "Mobile Branch", value: "29 discharges", share_of_total: "15%", commentary: "Below-average goal-met rate of 48% — clinical review recommended." },
      ],
      alerts: [
        { severity: "high", title: "Mobile Branch goal-met rate below 50%", detail: "48% goal-met discharge rate is significantly below the 62% network average.", recommended_action: "Initiate a clinical quality review for Mobile Branch focusing on care plan completion rates." },
      ],
      opportunities: [
        "Mobile Branch outcome improvement initiative could lift network-wide goal-met rate by 2-3 percentage points.",
        "The hospitalisation discharge reduction trend should be highlighted in quality reporting to referral sources.",
        "High-performing Charlotte and Raleigh practices could be documented as best-practice models for other branches.",
      ],
      data_quality_notes: ["Running in demo mode — data is illustrative only."],
      confidence: "low",
    },
  };

  return insightMap[kpi] ?? insightMap["admissions"];
}
